package arqSw.Hibernate;
// Generated 19/03/2017 10:22:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Artista generated by hbm2java
 */
public class Artista  implements java.io.Serializable {


     private Integer idArtista;
     private String usuario;
     private String clave;
     private Set<Estampa> estampas = new HashSet<Estampa>(0);

    public Artista() {
    }

    public Artista(String usuario, String clave, Set<Estampa> estampas) {
       this.usuario = usuario;
       this.clave = clave;
       this.estampas = estampas;
    }
   
    public Integer getIdArtista() {
        return this.idArtista;
    }
    
    public void setIdArtista(Integer idArtista) {
        this.idArtista = idArtista;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Set<Estampa> getEstampas() {
        return this.estampas;
    }
    
    public void setEstampas(Set<Estampa> estampas) {
        this.estampas = estampas;
    }




}


