package arqSw.Hibernate;
// Generated 19/03/2017 10:22:30 PM by Hibernate Tools 3.6.0



/**
 * Estampa generated by hbm2java
 */
public class Estampa  implements java.io.Serializable {


     private int idEstampa;
     private Tema tema;
     private Artista artista;
     private String nombre;
     private String descripcion;
     private String imagenes;
     private String tema_1;
     private String rating;
     private String popularidad;

    public Estampa() {
    }

	
    public Estampa(int idEstampa, Tema tema, Artista artista) {
        this.idEstampa = idEstampa;
        this.tema = tema;
        this.artista = artista;
    }
    public Estampa(int idEstampa, Tema tema, Artista artista, String nombre, String descripcion, String imagenes, String tema_1, String rating, String popularidad) {
       this.idEstampa = idEstampa;
       this.tema = tema;
       this.artista = artista;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.imagenes = imagenes;
       this.tema_1 = tema_1;
       this.rating = rating;
       this.popularidad = popularidad;
    }
   
    public int getIdEstampa() {
        return this.idEstampa;
    }
    
    public void setIdEstampa(int idEstampa) {
        this.idEstampa = idEstampa;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public Artista getArtista() {
        return this.artista;
    }
    
    public void setArtista(Artista artista) {
        this.artista = artista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getImagenes() {
        return this.imagenes;
    }
    
    public void setImagenes(String imagenes) {
        this.imagenes = imagenes;
    }
    public String getTema_1() {
        return this.tema_1;
    }
    
    public void setTema_1(String tema_1) {
        this.tema_1 = tema_1;
    }
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }
    public String getPopularidad() {
        return this.popularidad;
    }
    
    public void setPopularidad(String popularidad) {
        this.popularidad = popularidad;
    }




}


