package arqSw.Hibernate;
// Generated 19/03/2017 10:22:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private Integer idTema;
     private String descripcion;
     private Set<Estampa> estampas = new HashSet<Estampa>(0);

    public Tema() {
    }

	
    public Tema(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tema(String descripcion, Set<Estampa> estampas) {
       this.descripcion = descripcion;
       this.estampas = estampas;
    }
   
    public Integer getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(Integer idTema) {
        this.idTema = idTema;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Estampa> getEstampas() {
        return this.estampas;
    }
    
    public void setEstampas(Set<Estampa> estampas) {
        this.estampas = estampas;
    }




}


